/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.net.java.dev.jna.jna)
    api(libs.net.java.dev.jna.jna.platform)
    api(libs.com.github.kwhat.jnativehook)
}

description = "DrawingRust"
