/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("application")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}
javafx {
    version = "21"
    modules = listOf("javafx.controls")
}


description = "MediaPlayerFX"


application {
    mainClass.set("com.example.mediaplayerfx.HelloApplication")
}